name: Deploy Medusa Service

on:
  push:
    branches:
      - main  

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with : 
           aws-region: aws-region-1

      
      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/medusa-server:latest .
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/medusa-server:latest

      
      - name: Download Terraform
        uses: hashicorp/setup-terraform@v3

      
      - name: Terraform Init and Apply
        run: |
          terraform init
          terraform apply -auto-approve
